'\" t
.TH "GCLOUD\-DNS\-MANAGED\-ZONE\-CREATE" "1"
.ie \n(.g .ds Aq \(aq
.el       .ds Aq '
.nh
.ad l
.SH "NAME"
gcloud-dns-managed-zone-create \- Create a new Cloud DNS managed zone\&.
.SH "SYNOPSIS"
.sp
.nf
\fBgcloud dns managed\-zone create\fR
  ZONE
  [\-\-api_version API_VERSION]
  \-\-description DESCRIPTION
  \-\-dns_name DNS_NAME
  [\-\-format FORMAT]
  [\-\-help]
  [\-\-http_timeout HTTP_TIMEOUT]
  [\-\-log_http LOG_HTTP]
  [\-\-project PROJECT]
  [\-\-quiet, \-q]
  [\-\-trace_token TRACE_TOKEN]
  [\-h]
.fi
.SH "POSITIONAL ARGUMENTS"
.PP
\fIZONE\fR
.RS 4
Managed Zone name\&.
.RE
.SH "FLAGS"
.PP
\fB\-\-api_version\fR \fIAPI_VERSION\fR
.RS 4
API version\&. Optional\&.
.RE
.PP
\fB\-\-description\fR \fIDESCRIPTION\fR
.RS 4
Human readable description of this zone\&. Optional\&.
.RE
.PP
\fB\-\-dns_name\fR \fIDNS_NAME\fR
.RS 4
A domain name spec, for example "foo\&.bar\&.com\&."\&.
.RE
.PP
\fB\-\-format\fR \fIFORMAT\fR
.RS 4
Specify a format for printed output\&. By default, a command\-specific human\-friendly output format is used\&. Setting this flag to one of the available options will serialize the result of the command in the chosen format and print it to stdout\&. Supported formats are: "json", "text", "yaml"\&.
.RE
.PP
\fB\-\-help\fR
.RS 4
Display detailed help\&.
.RE
.PP
\fB\-\-http_timeout\fR \fIHTTP_TIMEOUT\fR
.RS 4
Timeout for HTTP network requests
.RE
.PP
\fB\-\-log_http\fR \fILOG_HTTP\fR
.RS 4
If true, log http requests\&.
.RE
.PP
\fB\-\-project\fR \fIPROJECT\fR
.RS 4
Google Cloud Platform project to use for this invocation\&.
.RE
.PP
\fB\-\-quiet\fR
.RS 4
Disable all interactive prompts when running gcloud commands\&. If input is required, defaults will be used, or an error will be raised\&.
.RE
.PP
\fB\-\-trace_token\fR \fITRACE_TOKEN\fR
.RS 4
Token for tracing API requests
.RE
.PP
\fB\-h\fR
.RS 4
Print a summary help and exit\&.
.RE
