'\" t
.TH "GCLOUD\-SQL\-OPERATIONS\-DESCRIBE" "1"
.ie \n(.g .ds Aq \(aq
.el       .ds Aq '
.nh
.ad l
.SH "NAME"
gcloud-sql-operations-describe \- Retrieves information about a Cloud SQL instance operation\&.
.SH "SYNOPSIS"
.sp
.nf
\fBgcloud sql operations describe\fR
  OPERATION
  [\-\-format FORMAT]
  [\-\-help]
  [\-\-instance INSTANCE, \-i INSTANCE]
  [\-\-project PROJECT]
  [\-\-quiet, \-q]
  [\-h]
.fi
.SH "POSITIONAL ARGUMENTS"
.PP
\fIOPERATION\fR
.RS 4
An identifier that uniquely identifies the operation\&.
.RE
.SH "FLAGS"
.PP
\fB\-\-format\fR \fIFORMAT\fR
.RS 4
Specify a format for printed output\&. By default, a command\-specific human\-friendly output format is used\&. Setting this flag to one of the available options will serialize the result of the command in the chosen format and print it to stdout\&. Supported formats are: "json", "text", "yaml"\&.
.RE
.PP
\fB\-\-help\fR
.RS 4
Display detailed help\&.
.RE
.PP
\fB\-\-instance\fR \fIINSTANCE\fR
.RS 4
Cloud SQL instance ID\&.
.RE
.PP
\fB\-\-project\fR \fIPROJECT\fR
.RS 4
Google Cloud Platform project to use for this invocation\&.
.RE
.PP
\fB\-\-quiet\fR
.RS 4
Disable all interactive prompts when running gcloud commands\&. If input is required, defaults will be used, or an error will be raised\&.
.RE
.PP
\fB\-h\fR
.RS 4
Print a summary help and exit\&.
.RE
