'\" t
.TH "GCLOUD\-COMPUTE\-INSTANCES\-SET\-SCHEDULING" "1"
.ie \n(.g .ds Aq \(aq
.el       .ds Aq '
.nh
.ad l
.SH "NAME"
gcloud-compute-instances-set-scheduling \- Set scheduling options for Google Compute Engine virtual machines
.SH "SYNOPSIS"
.sp
.nf
\fBgcloud compute instances set\-scheduling\fR
  INSTANCE
  [\-\-format FORMAT]
  [\-\-help]
  [\-\-maintenance\-policy MAINTENANCE_POLICY]
  [\-\-project PROJECT]
  [\-\-quiet, \-q]
  [\-\-no\-restart\-on\-failure | \-\-restart\-on\-failure]
  [\-\-zone ZONE]
  [\-h]
.fi
.SH "DESCRIPTION"
.sp
\fB$gcloud compute instances set\-scheduling\fR is used to configure scheduling options for Google Compute Engine virtual machines\&.
.SH "POSITIONAL ARGUMENTS"
.PP
\fIINSTANCE\fR
.RS 4
The name of the instance for which to change scheduling options\&.
.RE
.SH "FLAGS"
.PP
\fB\-\-format\fR \fIFORMAT\fR
.RS 4
Specify a format for printed output\&. By default, a command\-specific human\-friendly output format is used\&. Setting this flag to one of the available options will serialize the result of the command in the chosen format and print it to stdout\&. Supported formats are: "json", "text", "yaml"\&.
.RE
.PP
\fB\-\-help\fR
.RS 4
Display detailed help\&.
.RE
.PP
\fB\-\-maintenance\-policy\fR \fIMAINTENANCE_POLICY\fR
.RS 4
Specifies the behavior of the instances when their host machines undergo maintenance\&. TERMINATE indicates that the instances should be terminated\&. MIGRATE indicates that the instances should be migrated to a new host\&. Choosing MIGRATE will temporarily impact the performance of instances during a migration event\&.
.RE
.PP
\fB\-\-no\-restart\-on\-failure\fR
.RS 4
If provided, the instances will not be restarted automatically if they are terminated by the system\&. Mutually exclusive with \-\-restart\-on\-failure\&. This does not affect terminations performed by the user\&.
.RE
.PP
\fB\-\-project\fR \fIPROJECT\fR
.RS 4
Google Cloud Platform project to use for this invocation\&.
.RE
.PP
\fB\-\-quiet\fR
.RS 4
Disable all interactive prompts when running gcloud commands\&. If input is required, defaults will be used, or an error will be raised\&.
.RE
.PP
\fB\-\-restart\-on\-failure\fR
.RS 4
If provided, the instances will be restarted automatically if they are terminated by the system\&. This flag is mutually exclusive with \(lq\-\-no\-restart\-on\-failure\(rq\&. This does not affect terminations performed by the user\&.
.RE
.PP
\fB\-\-zone\fR \fIZONE\fR
.RS 4
The zone of the instance to set scheduling settings for\&. If not specified, you will be prompted to select a zone\&.
.sp
To avoid prompting when this flag is omitted, you can set the \(lqcompute/zone\(rq property:
.sp
.if n \{\
.RS 4
.\}
.nf
gcloud config set compute/zone ZONE
.fi
.if n \{\
.RE
.\}
.sp
A list of zones can fetched by running:
.sp
.if n \{\
.RS 4
.\}
.nf
gcloud compute zones list
.fi
.if n \{\
.RE
.\}
.sp
To unset the property, run:
.sp
.if n \{\
.RS 4
.\}
.nf
gcloud config unset compute/zone
.fi
.if n \{\
.RE
.\}
.sp
Alternatively, the zone can be stored in the environment variable \(lqCLOUDSDK_COMPUTE_ZONE\(rq\&.
.RE
.PP
\fB\-h\fR
.RS 4
Print a summary help and exit\&.
.RE
