'\" t
.TH "GCLOUD\-COMPUTE\-INSTANCES\-ADD\-METADATA" "1"
.ie \n(.g .ds Aq \(aq
.el       .ds Aq '
.nh
.ad l
.SH "NAME"
gcloud-compute-instances-add-metadata \- Add or update instance metadata
.SH "SYNOPSIS"
.sp
.nf
\fBgcloud compute instances add\-metadata\fR
  NAME
  [\-\-format FORMAT]
  [\-\-help]
  [\-\-metadata KEY=VALUE [KEY=VALUE \&...]]
  [\-\-metadata\-from\-file KEY=LOCAL_FILE_PATH [KEY=LOCAL_FILE_PATH \&...]]
  [\-\-project PROJECT]
  [\-\-quiet, \-q]
  [\-\-zone ZONE]
  [\-h]
.fi
.SH "DESCRIPTION"
.sp
gcloud compute instances add\-metadata can be used to add or update the metadata of a virtual machine instance\&. Every instance has access to a metadata server that can be used to query metadata that has been set through this tool\&. For information on metadata, see https://developers\&.google\&.com/compute/docs/metadata\&.
.sp
Only metadata keys that are provided are mutated\&. Existing metadata entries will remain unaffected\&.
.SH "POSITIONAL ARGUMENTS"
.PP
\fINAME\fR
.RS 4
The name of the instance whose metadata should be modified\&.
.RE
.SH "FLAGS"
.PP
\fB\-\-format\fR \fIFORMAT\fR
.RS 4
Specify a format for printed output\&. By default, a command\-specific human\-friendly output format is used\&. Setting this flag to one of the available options will serialize the result of the command in the chosen format and print it to stdout\&. Supported formats are: "json", "text", "yaml"\&.
.RE
.PP
\fB\-\-help\fR
.RS 4
Display detailed help\&.
.RE
.PP
\fB\-\-metadata\fR \fIKEY=VALUE [KEY=VALUE \&...]\fR
.RS 4
Metadata to be made available to the guest operating system running on the instances\&. Each metadata entry is a key/value pair separated by an equals sign\&. Metadata keys must be unique and less than 128 bytes in length\&. Values must be less than or equal to 32,768 bytes in length\&. Multiple arguments can be passed to this flag, e\&.g\&., \(lq\-\-metadata key\-1=value\-1 key\-2=value\-2 key\-3=value\-3\(rq\&.
.sp
In images that have
Compute Engine tools installed
on them, the following metadata keys have special meanings:
.PP
\fBstartup\-script\fR
.RS 4
Specifies a script that will be executed by the instances once they start running\&. For convenience, \(lq\-\-metadata\-from\-file\(rq can be used to pull the value from a file\&.
.RE
.PP
\fBstartup\-script\-url\fR
.RS 4
Same as \(lqstartup\-script\(rq except that the script contents are pulled from a publicly\-accessible location on the web\&.
.RE
.RE
.PP
\fB\-\-metadata\-from\-file\fR \fIKEY=LOCAL_FILE_PATH [KEY=LOCAL_FILE_PATH \&...]\fR
.RS 4
Same as \(lq\-\-metadata\(rq except that the value for the entry will be read from a local file\&. This is useful for values that are too large such as \(lqstartup\-script\(rq contents\&.
.RE
.PP
\fB\-\-project\fR \fIPROJECT\fR
.RS 4
Google Cloud Platform project to use for this invocation\&.
.RE
.PP
\fB\-\-quiet\fR
.RS 4
Disable all interactive prompts when running gcloud commands\&. If input is required, defaults will be used, or an error will be raised\&.
.RE
.PP
\fB\-\-zone\fR \fIZONE\fR
.RS 4
The zone of the instance to set metadata on\&. If not specified, you will be prompted to select a zone\&.
.sp
To avoid prompting when this flag is omitted, you can set the \(lqcompute/zone\(rq property:
.sp
.if n \{\
.RS 4
.\}
.nf
gcloud config set compute/zone ZONE
.fi
.if n \{\
.RE
.\}
.sp
A list of zones can fetched by running:
.sp
.if n \{\
.RS 4
.\}
.nf
gcloud compute zones list
.fi
.if n \{\
.RE
.\}
.sp
To unset the property, run:
.sp
.if n \{\
.RS 4
.\}
.nf
gcloud config unset compute/zone
.fi
.if n \{\
.RE
.\}
.sp
Alternatively, the zone can be stored in the environment variable \(lqCLOUDSDK_COMPUTE_ZONE\(rq\&.
.RE
.PP
\fB\-h\fR
.RS 4
Print a summary help and exit\&.
.RE
