'\" t
.TH "GCLOUD\-COMPUTE\-URL\-MAPS\-REMOVE\-HOST\-RULE" "1"
.ie \n(.g .ds Aq \(aq
.el       .ds Aq '
.nh
.ad l
.SH "NAME"
gcloud-compute-url-maps-remove-host-rule \- Remove a host rule from a URL map
.SH "SYNOPSIS"
.sp
.nf
\fBgcloud compute url\-maps remove\-host\-rule\fR
  NAME
  [\-\-delete\-orphaned\-path\-matcher]
  [\-\-format FORMAT]
  [\-\-help]
  \-\-host HOST
  [\-\-project PROJECT]
  [\-\-quiet, \-q]
  [\-h]
.fi
.SH "DESCRIPTION"
.sp
\fBgcloud compute url\-maps remove\-host\-rule\fR is used to remove a host rule from a URL map\&. When a host rule is removed, its path matcher is only removed if it is not referenced by any other host rules and \(lq\-\-delete\-orphaned\-path\-matcher\(rq is provided\&.
.SH "POSITIONAL ARGUMENTS"
.PP
\fINAME\fR
.RS 4
The name of the URL map\&.
.RE
.SH "FLAGS"
.PP
\fB\-\-delete\-orphaned\-path\-matcher\fR
.RS 4
If provided and a path matcher is orphaned as a result of this command, the command removes the orphaned path matcher instead of failing\&.
.RE
.PP
\fB\-\-format\fR \fIFORMAT\fR
.RS 4
Specify a format for printed output\&. By default, a command\-specific human\-friendly output format is used\&. Setting this flag to one of the available options will serialize the result of the command in the chosen format and print it to stdout\&. Supported formats are: "json", "text", "yaml"\&.
.RE
.PP
\fB\-\-help\fR
.RS 4
Display detailed help\&.
.RE
.PP
\fB\-\-host\fR \fIHOST\fR
.RS 4
One of the hosts in the host rule to remove\&.
.RE
.PP
\fB\-\-project\fR \fIPROJECT\fR
.RS 4
Google Cloud Platform project to use for this invocation\&.
.RE
.PP
\fB\-\-quiet\fR
.RS 4
Disable all interactive prompts when running gcloud commands\&. If input is required, defaults will be used, or an error will be raised\&.
.RE
.PP
\fB\-h\fR
.RS 4
Print a summary help and exit\&.
.RE
.SH "EXAMPLES"
.sp
To remove a host rule that contains the host \(lqgoogle\&.com\(rq from the URL map named \(lqmy\-url\-map\(rq, you can use this command:
.sp
.if n \{\
.RS 4
.\}
.nf
$ gcloud compute url\-maps remove\-host\-rule my\-url\-map \e
    \-\-host google\&.com
.fi
.if n \{\
.RE
.\}
