'\" t
.TH "GCLOUD\-COMPUTE\-DISKS\-SNAPSHOT" "1"
.ie \n(.g .ds Aq \(aq
.el       .ds Aq '
.nh
.ad l
.SH "NAME"
gcloud-compute-disks-snapshot \- Snapshot Google Compute Engine persistent disks
.SH "SYNOPSIS"
.sp
.nf
\fBgcloud compute disks snapshot\fR
  DISK_NAME [DISK_NAME \&...]
  [\-\-description DESCRIPTION]
  [\-\-format FORMAT]
  [\-\-help]
  [\-\-project PROJECT]
  [\-\-quiet, \-q]
  [\-\-snapshot\-names SNAPSHOT_NAME [SNAPSHOT_NAME \&...]]
  [\-\-zone ZONE]
  [\-h]
.fi
.SH "DESCRIPTION"
.sp
\fBgcloud compute disks snapshot\fR creates snapshots of persistent disks\&. Snapshots are useful for backing up data or copying a persistent disk\&.
.SH "POSITIONAL ARGUMENTS"
.PP
\fIDISK_NAME [DISK_NAME \&...]\fR
.RS 4
The names of the disks to snapshot\&.
.RE
.SH "FLAGS"
.PP
\fB\-\-description\fR \fIDESCRIPTION\fR
.RS 4
An optional, textual description for the snapshots being created\&.
.RE
.PP
\fB\-\-format\fR \fIFORMAT\fR
.RS 4
Specify a format for printed output\&. By default, a command\-specific human\-friendly output format is used\&. Setting this flag to one of the available options will serialize the result of the command in the chosen format and print it to stdout\&. Supported formats are: "json", "text", "yaml"\&.
.RE
.PP
\fB\-\-help\fR
.RS 4
Display detailed help\&.
.RE
.PP
\fB\-\-project\fR \fIPROJECT\fR
.RS 4
Google Cloud Platform project to use for this invocation\&.
.RE
.PP
\fB\-\-quiet\fR
.RS 4
Disable all interactive prompts when running gcloud commands\&. If input is required, defaults will be used, or an error will be raised\&.
.RE
.PP
\fB\-\-snapshot\-names\fR \fISNAPSHOT_NAME [SNAPSHOT_NAME \&...]\fR
.RS 4
Names to assign to the snapshots\&. Without this option, the name of each snapshot will be a random, 16\-character hexadecimal number that starts with a letter\&. The values of this option run parallel to the disks specified\&. For example,
.sp
.if n \{\
.RS 4
.\}
.nf
$ gcloud compute disks snapshot my\-disk\-1 my\-disk\-2 my\-disk\-3 \e
    \-\-snapshot\-name snapshot\-1 snapshot\-2 snapshot\-3
.fi
.if n \{\
.RE
.\}
.sp
will result in \(lqmy\-disk\-1\(rq being snapshotted as \(lqsnapshot\-1\(rq, \(lqmy\-disk\-2\(rq as \(lqsnapshot\-2\(rq, and so on\&.
.RE
.PP
\fB\-\-zone\fR \fIZONE\fR
.RS 4
The zone of the disks to snapshot\&. If not specified, you will be prompted to select a zone\&.
.sp
To avoid prompting when this flag is omitted, you can set the \(lqcompute/zone\(rq property:
.sp
.if n \{\
.RS 4
.\}
.nf
gcloud config set compute/zone ZONE
.fi
.if n \{\
.RE
.\}
.sp
A list of zones can fetched by running:
.sp
.if n \{\
.RS 4
.\}
.nf
gcloud compute zones list
.fi
.if n \{\
.RE
.\}
.sp
To unset the property, run:
.sp
.if n \{\
.RS 4
.\}
.nf
gcloud config unset compute/zone
.fi
.if n \{\
.RE
.\}
.sp
Alternatively, the zone can be stored in the environment variable \(lqCLOUDSDK_COMPUTE_ZONE\(rq\&.
.RE
.PP
\fB\-h\fR
.RS 4
Print a summary help and exit\&.
.RE
