'\" t
.TH "GCLOUD\-COMPUTE\-TARGET\-POOLS\-SET\-BACKUP" "1"
.ie \n(.g .ds Aq \(aq
.el       .ds Aq '
.nh
.ad l
.SH "NAME"
gcloud-compute-target-pools-set-backup \- Set a backup pool for a target pool
.SH "SYNOPSIS"
.sp
.nf
\fBgcloud compute target\-pools set\-backup\fR
  NAME
  \-\-backup\-pool [BACKUP_POOL]
  [\-\-failover\-ratio FAILOVER_RATIO]
  [\-\-format FORMAT]
  [\-\-help]
  [\-\-project PROJECT]
  [\-\-quiet, \-q]
  [\-\-region REGION]
  [\-h]
.fi
.SH "DESCRIPTION"
.sp
\fBgcloud compute target\-pools set\-backup\fR is used to set a backup target pool for a primary target pool, which defines the fallback behavior of the primary pool\&. If the ratio of the healthy instances in the primary pool is at or below the specified \(lq\-\-failover\-ratio value\(rq, then traffic arriving at the load\-balanced IP address will be directed to the backup pool\&.
.SH "POSITIONAL ARGUMENTS"
.PP
\fINAME\fR
.RS 4
The name of the target pool for which to set the backup pool\&.
.RE
.SH "FLAGS"
.PP
\fB\-\-backup\-pool\fR \fI[BACKUP_POOL]\fR
.RS 4
Name of the target pool that will serve as backup\&. If this flag is provided without a value, the existing backup pool is removed\&.
.RE
.PP
\fB\-\-failover\-ratio\fR \fIFAILOVER_RATIO\fR
.RS 4
The new failover ratio value for the target pool\&. This must be a float in the range of [0, 1]\&.
.RE
.PP
\fB\-\-format\fR \fIFORMAT\fR
.RS 4
Specify a format for printed output\&. By default, a command\-specific human\-friendly output format is used\&. Setting this flag to one of the available options will serialize the result of the command in the chosen format and print it to stdout\&. Supported formats are: "json", "text", "yaml"\&.
.RE
.PP
\fB\-\-help\fR
.RS 4
Display detailed help\&.
.RE
.PP
\fB\-\-project\fR \fIPROJECT\fR
.RS 4
Google Cloud Platform project to use for this invocation\&.
.RE
.PP
\fB\-\-quiet\fR
.RS 4
Disable all interactive prompts when running gcloud commands\&. If input is required, defaults will be used, or an error will be raised\&.
.RE
.PP
\fB\-\-region\fR \fIREGION\fR
.RS 4
The region of the target pool to set a backup pool for\&. If not specified, you will be prompted to select a region\&.
.sp
To avoid prompting when this flag is omitted, you can set the \(lqcompute/region\(rq property:
.sp
.if n \{\
.RS 4
.\}
.nf
gcloud config set compute/region REGION
.fi
.if n \{\
.RE
.\}
.sp
A list of regions can fetched by running:
.sp
.if n \{\
.RS 4
.\}
.nf
gcloud compute regions list
.fi
.if n \{\
.RE
.\}
.sp
To unset the property, run:
.sp
.if n \{\
.RS 4
.\}
.nf
gcloud config unset compute/region
.fi
.if n \{\
.RE
.\}
.sp
Alternatively, the region can be stored in the environment variable \(lqCLOUDSDK_COMPUTE_REGION\(rq\&.
.RE
.PP
\fB\-h\fR
.RS 4
Print a summary help and exit\&.
.RE
.SH "EXAMPLES"
.sp
To cause \(lqmy\-target\-pool\(rq (in region \(lqus\-central1\(rq) to fail over to \(lqmy\-backup\-pool\(rq when more than half of my\-target\-pool\(cqs instances are unhealthy, run:
.sp
.if n \{\
.RS 4
.\}
.nf
$ gcloud compute target\-pools set\-backup my\-target\-pool \e
    \-\-backup\-pool my\-backup\-pool \-\-failover\-ratio 0\&.5 \e
    \-\-region us\-central1
.fi
.if n \{\
.RE
.\}
.sp
To remove \(lqmy\-backup\-pool\(rq as a backup to \(lqmy\-target\-pool\(rq, run:
.sp
.if n \{\
.RS 4
.\}
.nf
$ gcloud compute target\-pools set\-backup my\-target\-pool \e
    \-\-backup\-pool \e
    \-\-region us\-central1
.fi
.if n \{\
.RE
.\}
