'\" t
.TH "GCLOUD\-COMPUTE\-ADDRESSES\-CREATE" "1"
.ie \n(.g .ds Aq \(aq
.el       .ds Aq '
.nh
.ad l
.SH "NAME"
gcloud-compute-addresses-create \- Reserve IP addresses
.SH "SYNOPSIS"
.sp
.nf
\fBgcloud compute addresses create\fR
  [NAME \&...]
  [\-\-addresses ADDRESS [ADDRESS \&...]]
  [\-\-description DESCRIPTION]
  [\-\-format FORMAT]
  [\-\-help]
  [\-\-project PROJECT]
  [\-\-quiet, \-q]
  [\-\-global | \-\-region REGION]
  [\-h]
.fi
.SH "DESCRIPTION"
.sp
\fBgcloud compute addresses create\fR is used to reserve one or more IP addresses\&. Once an IP address is reserved, it will be associated with the project until it is released using \fIgcloud compute addresses delete\fR\&. Ephemeral IP addresses that are in use by resources in the project, can be reserved using the \(lq\-\-addresses\(rq flag\&.
.SH "POSITIONAL ARGUMENTS"
.PP
\fI[NAME \&...]\fR
.RS 4
The names to assign to the reserved IP addresses\&.
.RE
.SH "FLAGS"
.PP
\fB\-\-addresses\fR \fIADDRESS [ADDRESS \&...]\fR
.RS 4
Ephemeral IP addresses to promote to reserved status\&. Only addresses that are being used by resources in the project can be promoted\&. When providing this flag, a parallel list of names for the addresses can be provided\&. For example,
.sp
.if n \{\
.RS 4
.\}
.nf
$ gcloud compute addresses create my\-address\-1 my\-address\-2 \e
    \-\-addresses 162\&.222\&.181\&.197 162\&.222\&.181\&.198 \e
    \-\-region us\-central1
.fi
.if n \{\
.RE
.\}
.RE
.sp
will result in 162\&.222\&.181\&.197 being reserved as \(lqmy\-address\-1\(rq and 162\&.222\&.181\&.198 as \(lqmy\-address\-2\(rq\&. If no names are given, randomly\-generated names will be assigned to the IP addresses\&.
.PP
\fB\-\-description\fR \fIDESCRIPTION\fR
.RS 4
An optional textual description for the addresses\&.
.RE
.PP
\fB\-\-format\fR \fIFORMAT\fR
.RS 4
Specify a format for printed output\&. By default, a command\-specific human\-friendly output format is used\&. Setting this flag to one of the available options will serialize the result of the command in the chosen format and print it to stdout\&. Supported formats are: "json", "text", "yaml"\&.
.RE
.PP
\fB\-\-global\fR
.RS 4
If provided, it is assumed the addresses are global\&.
.RE
.PP
\fB\-\-help\fR
.RS 4
Display detailed help\&.
.RE
.PP
\fB\-\-project\fR \fIPROJECT\fR
.RS 4
Google Cloud Platform project to use for this invocation\&.
.RE
.PP
\fB\-\-quiet\fR
.RS 4
Disable all interactive prompts when running gcloud commands\&. If input is required, defaults will be used, or an error will be raised\&.
.RE
.PP
\fB\-\-region\fR \fIREGION\fR
.RS 4
The region of the address to operate on\&. If not specified, you will be prompted to select a region\&.
.sp
To avoid prompting when this flag is omitted, you can set the \(lqcompute/region\(rq property:
.sp
.if n \{\
.RS 4
.\}
.nf
gcloud config set compute/region REGION
.fi
.if n \{\
.RE
.\}
.sp
A list of regions can fetched by running:
.sp
.if n \{\
.RS 4
.\}
.nf
gcloud compute regions list
.fi
.if n \{\
.RE
.\}
.sp
To unset the property, run:
.sp
.if n \{\
.RS 4
.\}
.nf
gcloud config unset compute/region
.fi
.if n \{\
.RE
.\}
.sp
Alternatively, the region can be stored in the environment variable \(lqCLOUDSDK_COMPUTE_REGION\(rq\&.
.RE
.PP
\fB\-h\fR
.RS 4
Print a summary help and exit\&.
.RE
.SH "EXAMPLES"
.sp
To reserve three IP addresses in the \(lqus\-central1\(rq region, run:
.sp
.if n \{\
.RS 4
.\}
.nf
$ gcloud compute addresses create my\-address\-1 my\-address\-2 my\-address\-3 \e
    \-\-region us\-central1
.fi
.if n \{\
.RE
.\}
.sp
To reserve ephemeral IP addresses 162\&.222\&.181\&.198 and 23\&.251\&.146\&.189 which are being used by virtual machine instances in the \(lqus\-central1\(rq region, run:
.sp
.if n \{\
.RS 4
.\}
.nf
$ gcloud compute addresses create \-\-addresses 162\&.222\&.181\&.198 23\&.251\&.146\&.189 \e
    \-\-region us\-central1
.fi
.if n \{\
.RE
.\}
.sp
In the above invocation, the two addresses will be assigned random names\&.
