'\" t
.TH "GCLOUD\-CONFIG\-LIST" "1"
.ie \n(.g .ds Aq \(aq
.el       .ds Aq '
.nh
.ad l
.SH "NAME"
gcloud-config-list \- List all currently available Cloud SDK properties associated with your current workspace or global configuration\&.
.SH "SYNOPSIS"
.sp
.nf
\fBgcloud config list\fR
  [PROPERTY]
  [\-\-all]
  [\-\-format FORMAT]
  [\-\-help]
  [\-\-project PROJECT]
  [\-\-quiet, \-q]
  [\-h]
.fi
.SH "POSITIONAL ARGUMENTS"
.PP
\fI[PROPERTY]\fR
.RS 4
The property to be listed\&.
.RE
.SH "FLAGS"
.PP
\fB\-\-all\fR
.RS 4
List all set and unset properties that match the arguments\&.
.RE
.PP
\fB\-\-format\fR \fIFORMAT\fR
.RS 4
Specify a format for printed output\&. By default, a command\-specific human\-friendly output format is used\&. Setting this flag to one of the available options will serialize the result of the command in the chosen format and print it to stdout\&. Supported formats are: "json", "text", "yaml"\&.
.RE
.PP
\fB\-\-help\fR
.RS 4
Display detailed help\&.
.RE
.PP
\fB\-\-project\fR \fIPROJECT\fR
.RS 4
Google Cloud Platform project to use for this invocation\&.
.RE
.PP
\fB\-\-quiet\fR
.RS 4
Disable all interactive prompts when running gcloud commands\&. If input is required, defaults will be used, or an error will be raised\&.
.RE
.PP
\fB\-h\fR
.RS 4
Print a summary help and exit\&.
.RE
